name: Build

on:
  push:
    branches: ["development"]
  pull_request:
    branches: ["development"]

jobs:
  build_frontend:
    defaults:
      run:
        working-directory: ./frontend/
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js LTS
      uses: actions/setup-node@v3
      with:
        node-version: "22.12.0"
        cache: 'npm'
        cache-dependency-path: 'frontend/package-lock.json'
    - run: npm install
    - run: npm run build --if-present

  build_backend:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: 1.20.2

      - name: Move event_data
        run: |
          cp -r event_data/ backend/

      - name: Linting Backend
        uses: golangci/golangci-lint-action@v3
        with:
          version: v1.53.3
          working-directory: ./backend
          args: --verbose

      - name: Build Backend
        run: |
          cd backend/
          go build -v

      - name: Test Backend
        run: |
          cd backend/
          go test -coverprofile=coverage.txt ./...

