name: Deploy to Production

on:
  release:
    types: [published]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Move event_data
        run: |
          cp -r event_data/ backend/
      - name: Install Railway CLI
        run: |
          curl -fsSL https://railway.app/install.sh | sh
      - name: Deploy to Railway
        env:
          RAILWAY_TOKEN: ${{ secrets.RAILWAY_TOKEN }}
        run: |
          cd backend
          railway variables --set RELEASE_VERSION=${{ github.event.release.tag_name }} --service owl-be-alt --skip-deploys
          railway up --service owl-be-alt
